version: 2.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Javadoc
          command: code/gradlew -q -p code/messaging javadocPublic
      - run:
          name: Build
          command: code/gradlew -p code/messaging assemblePhoneDebug
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: UnitTests
          command: code/gradlew -p code/messaging platformUnitTestJacocoReport
  publish:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Bintray Upload
          command: code/gradlew -p code/messaging bintrayUpload -PapiKey=$bintrayAPIKey -PgpgPassphrase=$gpgPassphrase
workflows:
  version: 2
  build-test-approve-and-publish:
    jobs:
      - build  
      - test:
          requires:
            - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
           - test
      - publish:
          requires:
            - hold
