version: 2.0
orbs:
  slack: circleci/slack@4.0.2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Javadoc
          command: code/gradlew -q -p code/analyticsedge javadocPublic
      - run:
          name: Build
          command: code/gradlew -p code/analyticsedge assemblePhoneDebug
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: UnitTests
          command: code/gradlew -p code/analyticsedge platformUnitTestJacocoReport
  # publish:
  #   working_directory: ~/code
  #   docker:
  #     - image: circleci/android:api-29
  #   environment:
  #     JVM_OPTS: -Xmx3200m
  #   steps:
  #     - checkout
  #     - run:
  #         name: Bintray Upload
  #         command: code/gradlew -p code/analyticsedge bintrayUpload -PapiKey=$bintrayAPIKey -PgpgPassphrase=$gpgPassphrase
workflows:
  version: 2
  build-test:
    jobs:
      - build  
      - test:
          requires:
            - build
      # - hold:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     type: approval
      #     requires:
      #      - test
      # - publish:
      #     requires:
      #       - hold
      # slack notification
      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL}
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Build Failed :x:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL}
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Build Successful :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }